Repository himanshusingh335/check_my_news, pull requests merged in 2021-10, with the labels that each got.

#3 💄 make logo background transparent
  assets/n.png
  pubspec.lock
Labels: enhancement

#5 Refactor: Create base services layer and dependency injections
  lib/components/searcBar.dart
  lib/config/endpoint.dart
  lib/constants/enum_constants.dart
  lib/injector.dart
  lib/main.dart
  lib/model/response/baseResponseModel.dart
  lib/screens/news_list_screen.dart
  lib/services/backend.dart
  lib/services/base/baseServices.dart
  lib/services/news/newsServices.dart
  pubspec.lock
  pubspec.yaml
Labels: hacktoberfest-accepted

#7 Add splash screen
  lib/constants/theme.dart
  lib/main.dart
  lib/screens/splash_screen.dart
Labels: enhancement, hacktoberfest-accepted
